[package]
name = "cheetiedotpy/wcs"
description = "Extensible framework that allows you create fully customizable combat systems easily by providing useful abstraction"
version = "0.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [".vscode", "src", "node_modules/*"]
include = ["include", "node_modules/@rbxts", "node_modules/@rbxts/*", "out", "default.project.json", "LICENSE"]

[dependencies]